### ISSUE TITLE
Vocup v2.0 roadmap

### ISSUE THREAD

**Issue by daniel-lerch** [daniel-lerch/vocup#27]
@Schafwolle this issue is for you, but it applies to anyone who wants to contribute to Vocup 😉

Thank you for your willingness to collaborate on Vocup. I opened this issue in order to discuss the work that has to be done for Vocup v2.0. That version is being developed on the `avalonia` branch of this repository.

Feel free to take a look at `Vocup.Core` and `Vocup.Avalonia`, the new main projects as well as `docs/fileformats.md` to see the all-new file format.

The rewrite is still in an early stage and there is much research work to be done. As I continue development I will open new issues and label them [_implementation_](https://github.com/daniel-lerch/vocup/issues?q=is%3Aissue+is%3Aopen+label%3Aimplementation) for components where I already know the most important requirements.

Please let me know if there is something that you would like to work on for that I have not written down requirements yet. For individual questions or a discussion about Vocup via video call you find my email address on [my GitHub profile](https://github.com/daniel-lerch).

**Comment by daniel-lerch** [comment]
The development of an Avalonia version of Vocup has been discontinued. Avalonia is missing too many features and provides no easy way for mobile support. Instead, I am looking into **.NET MAUI** as a future UI framework for Vocup.

In order to release new versions until a full rewrite is ready and also to practice the MVVM pattern, some controls will be rewritten with WPF.

**Comment by jdelange22** [comment]
Now that v2.0 is really out, I think this roadmap can be closed right?
