### ISSUE TITLE
Save window and column size 

### ISSUE THREAD

**Issue by Speciesx** [daniel-lerch/vocup#29]
Vocup doesn't save the window size, after every start i've to resize the Vocup window and the columns to my preference.

**Comment by daniel-lerch** [comment]
This missing feature should be directly implemented with #19 for Vocup 2.0.

If you would like to have this feature soon, feel free to implement it for 1.X by forking this repository and opening a pull request against the `master` branch. These values could easily be saved in `Vocup/Properties/Settings.settings` and loaded on start.

**Comment by daniel-lerch** [comment]
Thanks to @Schafwolle for implementing these features. @Speciesx I know that it would be possible to save the column width of the `VocubularyListView` but the resizing is already difficult there and I don't see a use of saving that as the width is adjusted automatically as you resize the form.
