### ISSUE TITLE
Support for Dutch UI language

### ISSUE THREAD

**Issue by jdelange22** [daniel-lerch/vocup#46]
I stubled upon your program and I really like it. One thing that I was missing though was support for the Dutch UI language so I translated the entire program into Dutch. Upon doing this, I also fixed some minor typos I found in the English resource files. If you're interested than I'm happy to create a pull request to add this feature.

**Comment by daniel-lerch** [comment]
Hi @jdelange22,
I would be more than happy about such a pull request.

**Comment by jdelange22** [comment]
@daniel-lerch PR has been submitted!
