### ISSUE TITLE
Word counters do not reset after unloading a vocabulary book

### ISSUE THREAD

**Issue by jdelange22** [daniel-lerch/vocup#47]
Like the title says, when unloading a vocabulary book, the word counters on the StatisticsPanel (bottom right) are not reset to zero. I can provide a PR with a fix for this if you like.
Fixes #47

**Comment by daniel-lerch** [comment]
Feel free to open a pull request for that, too.

**Comment by jdelange22** [comment]
@daniel-lerch  PR has been submitted!
