### ISSUE TITLE
Add default list of common Dutch special characters

### ISSUE THREAD

**Issue by jdelange22** [daniel-lerch/vocup#50]
With the recent upcoming addition of the Dutch UI language, I would also like to see a list of most common special characters of the Dutch language. I know I can add my own custom lists, but a build-in one is much more convenient. I can add this with a PR if you like.

**Comment by daniel-lerch** [comment]
@jdelange22 Thank you very much. I am very sorry that I could not review your pull requests yet. I am on holidays until easter and only have VS Code at hand for development.

**Comment by jdelange22** [comment]
No worries, enjoy your hollidays. I'll get notified whenever you got the time to look at the PR's
