### ISSUE TITLE
Inputfield doesn't get focus when first opening the special chars dialog

### ISSUE THREAD

**Issue by jdelange22** [daniel-lerch/vocup#51]
When practicing words and opening the special chars dialog (by pressing the button), the dialog appears and gets focussed. But when pressing the character buttons, no characters are entered in the input field. Only when manually placing the cursor in the inputfield allows special character input. Any further input is working fine as long as the focus is in the input field. So the issue only appears just after opening the dialog.

**Comment by jdelange22** [comment]
I also saw some wrong behaviour in the merge vocabulary book screen where the special chars button is enabled at load but no input fields are enabled. When pressing the button in that state, the button becomes disabled and no special char screen opens. I think in the merge screen, the special chars button should be disabled at load.

**Comment by daniel-lerch** [comment]
Do you consider it intuitive that the special char keyboard can be enabled or stays open even when no `TextBox` has focus? I thought about changing its behavior to match on-screen keyboards that users will be familiar with from smartphones. There, on-screen keyboards are only shown as long as the text input has focus and automatically hide afterwards.

**Comment by jdelange22** [comment]
@daniel-lerch I thought about your change, but I'm not sure. Might be distracting when practicing words that have basically no special chars in them. A window popping up and dissapearing all the time... To be honest. On screen keyboars popping up all the time when a input gets focus automatically is also kindof annoying.
The issues I've been fixing with the PR were:
- After opening the special characters dialog, the practice dialog gets focus automatically but the active (enabled) input doesn't get focus and the wrong input (disabled/readonly) gets bound to the character dialog. When you imediately start pressing special character buttons, no characters will be entered in the input field, because it is disabled or readonly. 
- In the merge screen, the inputs are both disabled, but the special chars button isn't. This is a minor glitch that upon pressing the button, no dialog gets opened but the button does get disabled, preventing the user from clicking it again.
